apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: https-ws
spec:
  containers:
  - name: httpd-container
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80